### ISSUE TITLE
Prelaunch checklist

### ISSUE THREAD

**Issue by JoshBroomberg** [iExperience/ixjourney#50]
- [ ] Switch the URL for the system from journey.ix to students.ix
 - Is this the URL we want for sure?
- Database
 - [ ] Upgrade the database to production size
 - [ ] Migrate data
- [ ] Upgrade the Web Dyno’s to 1 times 1X
- Test Segment
 - [ ] Test intercom messaging
 - [ ] Test intercom user sync - investigate update name bug when JS/server libraries interact.
 - [ ] Test FB event capture
